variable "manage_databases" {
  description = "Creates the databases, users and grants. Needs network reach to the DB system."
  type        = bool
  default     = false
}

variable "db_host" {
  description = "Address the mysql provider connects to. Defaults to the DB system's DNS name."
  type        = string
  default     = null
}

variable "db_tls" {
  type    = string
  default = "skip-verify"
}

variable "applications" {
  description = "Applications keyed by name. Each one: db_user, db_name, optional db_host, optional databases, optional grants."
  type        = any
  default     = {}
}

variable "app_passwords" {
  description = "Password per application key, generated by the platform module."
  type        = map(string)
  default     = {}
  sensitive   = true
}

variable "default_grants" {
  type    = list(string)
  default = ["SELECT", "INSERT", "UPDATE", "DELETE", "EXECUTE"]
}

variable "database_character_set" {
  type    = string
  default = "utf8mb4"
}

variable "database_collation" {
  type    = string
  default = "utf8mb4_general_ci"
}
