[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*(?:lvl|level)=\S+.*(?i:invalid username or password).*remote_addr=<HOST>.*$
            ^.*(?:lvl|level)=\S+.*(?i:failed to authenticate request).*remote_addr=<HOST>.*$
            ^.*(?:lvl|level)=\S+.*(?i:invalid api key).*remote_addr=<HOST>.*$

ignoreregex =

datepattern = ^t=%%Y-%%m-%%dT%%H:%%M:%%S%%z
              ^logger=\S+ t=%%Y-%%m-%%dT%%H:%%M:%%S%%z
              %%Y-%%m-%%dT%%H:%%M:%%S
