---
- name: restart observability
  community.docker.docker_compose_v2:
    project_src: "{{ observability_dir }}"
    state: restarted

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
