---
all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

  children:
    role_app:
      hosts:
        192.168.122.11:

    role_monitoring:
      hosts:
        192.168.122.10:

    env_local:
      children:
        role_app:
        role_monitoring:
