plugin: oracle.oci.oci

auth_type: instance_principal

regions:
  - sa-saopaulo-1

compartments:
  - compartment_ocid: "ocid1.tenancy.oc1..aaaaaaaa5lalh56ffqq2aorknmx3aokh5pekgj5hkplpbroue6ljcpdwqrtq"
    fetch_hosts_from_subcompartments: false

instance_states:
  - RUNNING

include_host_filters:
  - >-
    defined_tags.get('pscloud', {}).get('environment') == 'prod' and
    defined_tags.get('pscloud', {}).get('role', '') in ['app', 'monitoring']

hostname_format: private_ip

keyed_groups:
  - key: defined_tags['pscloud']['role']
    prefix: role
    separator: "_"
  - key: freeform_tags['pscloud_pool'] | default('none')
    prefix: pool
    separator: "_"

compose:
  ansible_host: private_ip
  oci_display_name: display_name
  oci_fault_domain: fault_domain
