---
timezone: America/Sao_Paulo

base_packages:
  - jq
  - curl
  - ca-certificates
  - unzip
  - tar
  - sysstat
  - python3-debian
  - iptables-persistent
  - acl

base_open_ports: []

base_users:
  deploy:
    comment: Deployment automation
    sudo: ["ALL"]
    ssh_keys: []

  ops:
    comment: Read-only operations
    groups: [systemd-journal, adm]
    sudo:
      - /usr/bin/systemctl status *
      - /usr/bin/systemctl is-active *
      - /usr/bin/systemctl show *
      - /usr/bin/systemctl cat *
      - /usr/bin/systemctl list-units *
      - /usr/bin/systemctl restart dotnet-app@*
      - /usr/bin/journalctl *
      - /usr/bin/systemd-cgtop *
      - /usr/bin/systemd-analyze *
    ssh_keys: []

journald_settings:
  Storage: persistent
  Compress: "yes"
  SystemMaxUse: 512M
  SystemMaxFileSize: 64M
  RuntimeMaxUse: 64M
  MaxRetentionSec: 7day
  RateLimitIntervalSec: 30s
  RateLimitBurst: 20000
  ForwardToSyslog: "no"
