---
app_env: prod

host_vcpus: 2
host_memory_mb: 6144
apps_slice_reserve_mb: 1600

oci_auth_type: instance_principal

db_create_schemas: false

ansible_user: ubuntu
ssh_key_role: "{{ 'monitoring' if 'role_monitoring' in group_names else 'app' }}"
ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/pscloud-{{ ssh_key_role }}"
