#!/usr/bin/env python3
"""Artifacts and secrets, on OCI.

Authentication is automatic and is the only difference between a laptop, a
local VM and a machine in OCI:

    ~/.oci/config exists  ->  use it
    otherwise             ->  instance principal

    pscloud push    <name> <version> <file>   upload an artifact (CI)
    pscloud fetch   <name> <version> <dir>    download and unpack it
    pscloud secret  <name>                    print a secret, creating it if absent
    pscloud env     <dir>                     resolve @@name@@ in *.env.template
"""
import base64
import glob
import os
import pathlib
import re
import secrets
import subprocess
import sys
import tempfile

import oci

BUCKET = os.environ["PSCLOUD_BUCKET"]
COMPARTMENT = os.environ["PSCLOUD_COMPARTMENT"]
VAULT = os.environ.get("PSCLOUD_VAULT", "")
VAULT_KEY = os.environ.get("PSCLOUD_VAULT_KEY", "")


def auth():
    cfg = os.path.expanduser("~/.oci/config")
    if os.path.exists(cfg):
        return {"config": oci.config.from_file()}
    return {"config": {},
            "signer": oci.auth.signers.InstancePrincipalsSecurityTokenSigner()}


def object_name(name, version):
    return f"artifacts/{name}/{name}-{version}.tar.gz"


def push(name, version, path):
    os_client = oci.object_storage.ObjectStorageClient(**auth())
    ns = os_client.get_namespace().data
    obj = object_name(name, version)
    with open(path, "rb") as fh:
        os_client.put_object(ns, BUCKET, obj, fh)
    print(obj)


def fetch(name, version, dest):
    os_client = oci.object_storage.ObjectStorageClient(**auth())
    ns = os_client.get_namespace().data
    obj = object_name(name, version)
    pathlib.Path(dest).mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(suffix=".tar.gz") as tmp:
        r = os_client.get_object(ns, BUCKET, obj)
        for chunk in r.data.raw.stream(1024 * 1024, decode_content=False):
            tmp.write(chunk)
        tmp.flush()
        subprocess.run(["tar", "-xzf", tmp.name, "-C", dest], check=True)
    print(f"{obj} -> {dest}")


def secret(name):
    """Read a secret, generating and storing one on first use."""
    kw = auth()
    vaults = oci.vault.VaultsClient(**kw)
    found = vaults.list_secrets(compartment_id=COMPARTMENT, vault_id=VAULT,
                                name=name, lifecycle_state="ACTIVE").data
    if found:
        bundles = oci.secrets.SecretsClient(**kw)
        b = bundles.get_secret_bundle(found[0].id, stage="CURRENT").data
        return base64.b64decode(b.secret_bundle_content.content).decode()

    value = "".join(secrets.choice(
        "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
        for _ in range(32))
    vaults.create_secret(oci.vault.models.CreateSecretDetails(
        compartment_id=COMPARTMENT, vault_id=VAULT, key_id=VAULT_KEY,
        secret_name=name, description="generated by pscloud",
        secret_content=oci.vault.models.Base64SecretContentDetails(
            content_type="BASE64",
            content=base64.b64encode(value.encode()).decode()),
    ))
    return value


def resolve_env(directory):
    """Substitute @@secret-name@@ in every *.env.template in a directory."""
    import grp
    gid = grp.getgrnam(os.environ.get("PSCLOUD_APP_GROUP", "dotnetapp")).gr_gid
    cache = {}

    def value(m):
        n = m.group(1)
        if n not in cache:
            cache[n] = secret(n)
        return cache[n]

    for tpl in sorted(glob.glob(f"{directory}/*.env.template")):
        out = pathlib.Path(tpl[: -len(".template")])
        out.write_text(re.sub(r"@@([A-Za-z0-9_.-]+)@@", value,
                              pathlib.Path(tpl).read_text()))
        os.chown(out, 0, gid)
        os.chmod(out, 0o640)
        print(f"wrote {out}")


cmd, *args = sys.argv[1:] or ["-h"]
if cmd == "push":
    push(*args)
elif cmd == "fetch":
    fetch(*args)
elif cmd == "secret":
    print(secret(*args))
elif cmd == "env":
    resolve_env(*args)
else:
    sys.exit(__doc__)
