{
 "title": "MySQL 8.0 Overview",
 "description": "Dashboard for MySQL Monitoring from prometheus mysql exporter.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(mysql_up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mysql_up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "2m, 5m, 10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Command Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL Connected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Connected"
    }
   ]
  },
  {
   "title": "Select Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\", job=\"$job\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Select"
    }
   ]
  },
  {
   "title": "Update Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\", job=\"$job\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "Insert Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\", job=\"$job\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Update"
    }
   ]
  },
  {
   "title": "Delete Command",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\", job=\"$job\", instance=\"$instance\"}[$__interval])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "System Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL Instance Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MySQL Uptime - $instance",
   "type": "stat",
   "description": "**MySQL Uptime**",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "MySQL Version - $instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "mysql_version_info{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Current QPS - $instance",
   "type": "stat",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"$instance\",job=\"$job\"}[$interval])"
    }
   ]
  },
  {
   "title": "QPS Respoectively (Top 5) - $instance",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$instance\",job=\"$job\"}[$interval])>0 or irate(mysql_global_status_commands_total{instance=\"$instance\",job=\"$job\"}[5m])>0)",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic - $instance",
   "type": "timeseries",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{instance=\"$instance\",job=\"$job\"}[$interval]) or irate(mysql_global_status_bytes_received{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "InBound"
    },
    {
     "expr": "0 - rate(mysql_global_status_bytes_sent{instance=\"$instance\",job=\"$job\"}[$interval]) or irate(mysql_global_status_bytes_sent{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "OutBound"
    }
   ]
  },
  {
   "title": "Aborted Connects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 49 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_clients{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Abort Clients"
    },
    {
     "expr": "irate(mysql_global_status_aborted_connects{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Aborted Connects"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity - $instance",
   "type": "timeseries",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Peak Threads Running"
    },
    {
     "expr": "avg_over_time(mysql_global_status_threads_running{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Avg Threads Running"
    }
   ]
  },
  {
   "title": "Threads Status - $instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_cached{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "mysql_global_status_threads_connected{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Connected"
    },
    {
     "expr": "mysql_global_status_threads_created{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Created"
    },
    {
     "expr": "mysql_global_status_threads_running{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Open Tables - $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_open_tables{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Open Files - $instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_open_files{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(mysql_global_status_threads_created{instance=\"$instance\",job=\"$job\"}[$interval])/max_over_time(mysql_global_status_connections{instance=\"$instance\",job=\"$job\"}[$interval])) * 100.0"
    }
   ]
  },
  {
   "title": "Connection Miss Rate(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(mysql_global_status_aborted_connects{instance=\"$instance\",job=\"$job\"}[$interval])/max_over_time(mysql_global_status_connections{instance=\"$instance\",job=\"$job\"}[$interval])) * 100.0"
    }
   ]
  },
  {
   "title": "Connection Usage(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(irate(mysql_global_status_connections{instance=\"$instance\",job=\"$job\"}[$interval])/mysql_global_variables_max_connections{instance=\"$instance\",job=\"$job\"}) * 100.0"
    }
   ]
  },
  {
   "title": "Process States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc,state) (max_over_time(mysql_info_schema_processlist_threads{instance=\"$instance\",job=\"$job\"}[$__interval]) or max_over_time(mysql_info_schema_processlist_threads{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Table Open Cache - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_opened_tables{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Opening"
    },
    {
     "expr": "irate(mysql_global_status_table_open_cache_hits{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "irate(mysql_global_status_table_open_cache_misses{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Cache Misses"
    }
   ]
  },
  {
   "title": "Table Locks - $instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 57 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_table_locks_immediate{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Table locks immediate"
    },
    {
     "expr": "irate(mysql_global_status_table_locks_waited{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Table locks waited"
    }
   ]
  },
  {
   "title": "Select Type - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_select_scan{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Select Scan"
    },
    {
     "expr": "irate(mysql_global_status_select_full_join{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Select Full Join"
    },
    {
     "expr": "irate(mysql_global_status_select_full_range_join{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Select Full Range Join"
    },
    {
     "expr": "irate(mysql_global_status_select_range{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Select Range"
    },
    {
     "expr": "irate(mysql_global_status_select_range_check{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Select Range Check"
    }
   ]
  },
  {
   "title": "Sort - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_sort_rows{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Sort Rows"
    },
    {
     "expr": "irate(mysql_global_status_sort_scan{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Sort Scan"
    },
    {
     "expr": "irate(mysql_global_status_sort_merge_passes{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Sort Merge Passes"
    },
    {
     "expr": "irate(mysql_global_status_sort_range{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Sort Range"
    }
   ]
  },
  {
   "title": "Temporary Object - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_created_tmp_tables{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Created tmp tables"
    },
    {
     "expr": "irate(mysql_global_status_created_tmp_disk_tables{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Created tmp disk tables"
    },
    {
     "expr": "irate(mysql_global_status_created_tmp_files{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Created tmp files"
    }
   ]
  },
  {
   "title": "Transactional Handlers - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_handlers_total{instance=\"$instance\",job=\"$job\",handler=~\"commit|prepare|rollback|savepoint|savepoint_rollback\"}[$interval])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Handlers - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_handlers_total{instance=\"$instance\",job=\"$job\",handler!~\"commit|prepare|rollback|savepoint|savepoint_rollback\"}[$interval]) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Binlog Cache - $instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_binlog_cache_use{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Binlog cache use"
    },
    {
     "expr": "irate(mysql_global_status_binlog_cache_disk_use{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Binlog cache disk use"
    },
    {
     "expr": "irate(mysql_global_status_binlog_stmt_cache_disk_use{instance=\"$instance\",job=\"$job\"}[$interval])",
     "legendFormat": "Binlog stmt cache disk use"
    }
   ]
  },
  {
   "title": "Memory Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "InnoDB Pool Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "InnoDB Old Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_old_blocks_pct{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Key Buffer Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "InnoDB Log Buffer Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "InnoDB Sort Buffer Size",
   "type": "stat",
   "description": "This Buffer is used for Buidling InnoDB Indexes using Sort algorithm",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_sort_buffer_size{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "BP Usage(%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_buffer_pool_pages{instance=\"$instance\",job=\"$job\",state=\"data\"} / on (instance) (mysql_global_status_buffer_pool_pages{instance=\"$instance\",job=\"$job\",state=\"data\"} + on (instance) mysql_global_status_buffer_pool_pages{instance=\"$instance\",job=\"$job\",state=\"free\"} + on (instance) mysql_global_status_buffer_pool_pages{instance=\"$instance\",job=\"$job\",state=\"misc\"}) * 100.0"
    }
   ]
  },
  {
   "title": "BP Write Activity",
   "type": "stat",
   "description": "Combined value of Buffer Pool Read and Write requests",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (irate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"$instance\",job=\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Data Buffer Pool Fit",
   "type": "stat",
   "description": "Buffer Pool Size as Portion of the Data",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mysql_global_variables_innodb_buffer_pool_size{job=\"$job\", instance=\"$instance\"})/sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=~\"data_length|index_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Buffer Pool Miss Ratio",
   "type": "stat",
   "description": "How often buffer pool read requests have to do read from the disk. Keep this percent low for good performance",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (irate(mysql_global_status_innodb_buffer_pool_reads{instance=\"$instance\",job=\"$job\"}[$interval])/irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$instance\", job=\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Indexing Overhead",
   "type": "stat",
   "description": "How Much Indexes Take Compared to Data",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=\"index_length\"}) by (schema,table)))/(sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\", engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=\"data_length\"}) by (schema,table)))"
    }
   ]
  },
  {
   "title": "InnoDB Tables",
   "type": "stat",
   "description": "Current Number of InnoDB Tables in database",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"})"
    }
   ]
  },
  {
   "title": "InnoDB Open Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_info_schema_innodb_metrics_file_system_file_num_open_files{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "InnoDB File Per Table",
   "type": "stat",
   "description": "If Enabled, By Default every Table will have its own Tablespace represented as its own .idb file  rather than all tables stored in single system tablespace",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (mysql_global_variables_innodb_file_per_table{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Space Allocated",
   "type": "stat",
   "description": "Total Amount of Space Allocated.    May not exactly match amount of space used on file system but provided great guidance",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Space Used",
   "type": "stat",
   "description": "Space used in All  InnoDB Tables.   Reported Allocated Space Less Free Space",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=~\"data_length|index_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Data Length",
   "type": "stat",
   "description": "Space Used by Data (Including Primary Key)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=\"data_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Index Length",
   "type": "stat",
   "description": "Space Used by Secondary Indexes",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=\"index_length\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Free",
   "type": "stat",
   "description": "How Much Space is Free. Too high value wastes space on disk",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=\"data_free\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Estimated Rows",
   "type": "stat",
   "description": "Estimated number of Rows in InnoDB Storage Engine. It is not exact value and it can change abruptly as information is updated",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_rows{job=\"$job\", instance=\"$instance\"}) by (schema,table))"
    }
   ]
  },
  {
   "title": "Data Size Per Row",
   "type": "stat",
   "description": "Amount of Data Per Row",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum(mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=\"data_length\"}) by (schema,table)) / (sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_rows{job=\"$job\", instance=\"$instance\"}) by (schema,table)))"
    }
   ]
  },
  {
   "title": "Index Size Per Row",
   "type": "stat",
   "description": "Index Size Per Row shows how much space we're using for indexes on per row basics",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum(mysql_info_schema_table_size{job=\"$job\", instance=\"$instance\",component=\"index_length\"}) by (schema,table)) / (sum(count(mysql_info_schema_table_version{job=\"$job\", instance=\"$instance\",engine=\"InnoDB\"}) by (schema,table) * sum (mysql_info_schema_table_rows{job=\"$job\", instance=\"$instance\"}) by (schema,table)))"
    }
   ]
  },
  {
   "title": "Portion of Buffer Pool To Dump/Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * avg by (desc) (mysql_global_variables_innodb_buffer_pool_dump_pct{job=\"$job\", instance=\"$instance\"}/100)"
    }
   ]
  },
  {
   "title": "InnoDB Dedicated Server",
   "type": "stat",
   "description": "InnoDB automatically optimized for Dedicated Server Environment (auto scaling cache and some other variables)",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_dedicated_server{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "InnoDB Stats Auto Recalc",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_auto_recalc{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Update Stats when Metadata Queried",
   "type": "stat",
   "description": "Refresh InnoDB Statistics when meta-data queries by SHOW TABLE STATUS or INFORMATION_SCHEMA queries.  If Enabled can cause severe performance issues",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_on_metadata{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "InnoDB Persistent Statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_persistent{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "InnoDB Persistent Sample Pages",
   "type": "stat",
   "description": "Number of Pages To Sample if Persistent Statistics are Enabled",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_persistent_sample_pages{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "InnoDB Transient Sample Pages",
   "type": "stat",
   "description": "Number of Pages To Sample if Persistent Statistics are Disabled",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_stats_transient_sample_pages{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  { "title": "InnoDB Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc,state) (max_over_time(mysql_global_status_buffer_pool_pages{job=\"$job\", instance=\"$instance\", state=~\"free|data|misc\"}[$__interval]) or max_over_time(mysql_global_status_buffer_pool_pages{job=\"$job\", instance=\"$instance\", state=~\"free|data|misc\"}[5m]))",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (desc) (avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{job=\"$job\", instance=\"$instance\"}[$__interval]) or avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Data Total"
    },
    {
     "expr": "avg by (desc) (avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_dirty{job=\"$job\", instance=\"$instance\"}[$__interval]) or avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_dirty{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Data Dirty"
    },
    {
     "expr": "avg by (desc) (sum((avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{job=\"$job\", instance=\"$instance\"}[$__interval]) or avg_over_time(mysql_global_status_innodb_buffer_pool_bytes_data{job=\"$job\", instance=\"$instance\"}[5m])))*sum(mysql_global_variables_innodb_max_dirty_pages_pct{job=\"$job\", instance=\"$instance\"})/100)",
     "legendFormat": "Estimatred Dirty Data Limit"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Page Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_pages_created{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_pages_created{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Pages Created"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_pages_read{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_pages_read{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Pages Read"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_pages_written{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_pages_written{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Pages Written"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_requests{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_requests{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Read Requests"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_write_requests{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_write_requests{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Write Requests"
    }
   ]
  },
  {
   "title": "InnoDB Read-Ahead",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_ahead{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Pages Fetched by Linear Read Ahead"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_rnd{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Paged Fetched by Random Read Ahead"
    },
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{job=\"$job\", instance=\"$instance\"}[$__interval]) or irate(mysql_global_status_innodb_buffer_pool_read_ahead_evicted{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Paged Fetched by Read Ahead but Never Accessed"
    }
   ]
  },
  {
   "title": "InnoDB Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{job=\"$job\",instance=\"$instance\"}[$__interval]) or irate(mysql_info_schema_innodb_metrics_server_innodb_activity_count_total{job=\"$job\",instance=\"$instance\"}[5m]))",
     "legendFormat": "InnoDB Activity"
    }
   ]
  },
  {
   "title": "InnoDB Row Reads",
   "type": "timeseries",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_row_ops_total{job=\"$job\", instance=\"$instance\",operation=\"read\"}[$__interval]) or irate(mysql_global_status_innodb_row_ops_total{desc=\"Systemv 그룹\",project=\"systemv_group\",operation=\"read\"}[5m]))",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "InnoDB Row Writes",
   "type": "timeseries",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc,operation) (rate(mysql_global_status_innodb_row_ops_total{job=\"$job\", instance=\"$instance\",operation!=\"read\"}[$__interval]) or irate(mysql_global_status_innodb_row_ops_total{job=\"$job\", instance=\"$instance\",operation!=\"read\"}[5m]))",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  { "title": "InnoDB Locking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Lock Wait Timeout",
   "type": "stat",
   "description": "** InnoDB Lock Wait Timeout **\nHow long to wait for row lock before timing out",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_lock_wait_timeout{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "InnoDB Deadlock Detection",
   "type": "stat",
   "description": "If Disabled InnoDB Will not detect deadlocks but rely on timeouts",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_deadlock_detect{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "InnoDB Auto Increment Lock Mode",
   "type": "stat",
   "description": "Will Define How mush locking will come from working with Auto Increment Columns",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_variables_innodb_deadlock_detect{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rollback on Timeout",
   "type": "stat",
   "description": "Whenever to rollback all transaction on timeout or just last statement",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (mysql_global_variables_innodb_rollback_on_timeout{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Row Lock Blocking",
   "type": "stat",
   "description": "Percent of Active Sections which are blocked due to waiting on InnoDB Row Locks",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) ((rate(mysql_global_status_innodb_row_lock_time{instance=\"$instance\",job=\"$job\"}[$__interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{instance=\"$instance\",job=\"$job\"}[5m])/1000)/((avg_over_time(mysql_global_status_threads_running{instance=\"$instance\",job=\"$job\"}[$__interval]))or (avg_over_time(mysql_global_status_threads_running{instance=\"$instance\",job=\"$job\"}[5m]))))"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Wait Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (desc) (rate(mysql_global_status_innodb_row_lock_waits{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_row_lock_waits{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Lock Waits"
    },
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_deadlocks{instance=\"$instance\",job=\"$job\"}[$__interval]) or rate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{instance=\"$instance\",job=\"$job\"}[$__interval])) or (irate(mysql_global_status_innodb_deadlocks{instance=\"$instance\",job=\"$job\"}[5m]) or irate(mysql_info_schema_innodb_metrics_lock_lock_deadlocks_total{instance=\"$instance\",job=\"$job\"}[5m])))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "avg by (desc) (rate(mysql_info_schema_innodb_metrics_lock_lock_timeouts_total{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_timeouts_total{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Lock Wait Timeouts"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_row_lock_time{instance=\"$instance\",job=\"$job\"}[$__interval])/rate(mysql_global_status_innodb_row_lock_waits{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_row_lock_time{instance=\"$instance\",job=\"$job\"}[5m])/irate(mysql_global_status_innodb_row_lock_waits{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Avg Row Lock Wait Time"
    }
   ]
  },
  {
   "title": "InnoDB Row Lock Wait Load",
   "type": "timeseries",
   "description": "Average Number of Sessions blocked from proceeding due to waiting on row level lock",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_row_lock_time{instance=\"$instance\",job=\"$job\"}[$__interval])/1000 or irate(mysql_global_status_innodb_row_lock_time{instance=\"$instance\",job=\"$job\"}[5m])/1000)",
     "legendFormat": "Row Lock Wait Load"
    },
    {
     "expr": "avg by (service_name) (((avg_over_time(mysql_global_status_threads_running{instance=\"$instance\",job=\"$job\"}[$__interval]))or (avg_over_time(mysql_global_status_threads_running{instance=\"$instance\",job=\"$job\"}[5m]))))",
     "legendFormat": "MySQL Threads Active"
    }
   ]
  },
  { "title": "InnoDB Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "InnoDB Page Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) (mysql_global_status_innodb_page_size{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Avg Data Read Rq Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[5m]))/(rate(mysql_global_status_innodb_data_reads{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_reads{instance=\"$instance\",job=\"$job\"}[5m])))"
    }
   ]
  },
  {
   "title": "Avg Data Write Rq Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[5m]))/(rate(mysql_global_status_innodb_data_writes{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_writes{instance=\"$instance\",job=\"$job\"}[5m])))"
    }
   ]
  },
  {
   "title": "Avg Log Write Rq Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_os_log_written{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_written{instance=\"$instance\",job=\"$job\"}[5m]))/(rate(mysql_global_status_innodb_log_writes{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_log_writes{instance=\"$instance\",job=\"$job\"}[5m])))"
    }
   ]
  },
  {
   "title": "Data Written Per Fsync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[5m]))/(rate(mysql_global_status_innodb_data_fsyncs{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_fsyncs{instance=\"$instance\",job=\"$job\"}[5m])))"
    }
   ]
  },
  {
   "title": "Log Written Per Fsync",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (desc) ((rate(mysql_global_status_innodb_os_log_written{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_written{instance=\"$instance\",job=\"$job\"}[5m]))/(rate(mysql_global_status_innodb_os_log_fsyncs{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=\"$instance\",job=\"$job\"}[5m])))"
    }
   ]
  },
  {
   "title": "Data Read Per Row Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((rate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[5m])))/ sum((rate(mysql_global_status_innodb_row_ops_total{instance=\"$instance\",job=\"$job\",operation=\"read\"}[$__interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=\"$instance\",job=\"$job\",operation=\"read\"}[5m])))"
    }
   ]
  },
  {
   "title": "Data Written Per Row Written",
   "type": "stat",
   "description": "Note: Due to difference in timing of Row Write and Data Write the value may be misleading on short intervals",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[$__interval]))/sum(rate(mysql_global_status_innodb_row_ops_total{instance=\"$instance\",job=\"$job\",operation!=\"read\"}[$__interval]))  or sum(irate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[5m]))/sum(irate(mysql_global_status_innodb_row_ops_total{instance=\"$instance\",job=\"$job\",operation!=\"read\"}[5m]))"
    }
   ]
  },
  {
   "title": "InnoDB Data Bandwitdh",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Data Read"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Data Written"
    },
    {
     "expr": "avg by (service_name) ((rate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_read{instance=\"$instance\",job=\"$job\"}[5m]))+ (rate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_written{instance=\"$instance\",job=\"$job\"}[5m])))",
     "legendFormat": "Data Total Bandwith"
    }
   ]
  },
  {
   "title": "InnoDB Log IO",
   "type": "timeseries",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes._Data Reads_ - The total number of InnoDB data reads (OS file reads)._Log Writes_ - The number of physical writes to the InnoDB redo log file._Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_log_writes{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_log_writes{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Log Writes"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_os_log_written{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_written{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Log Written"
    }
   ]
  },
  {
   "title": "InnoDB FSyncs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_data_fsyncs{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_data_fsyncs{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Data Fsyncs"
    },
    {
     "expr": "avg by (service_name) (rate(mysql_global_status_innodb_os_log_fsyncs{instance=\"$instance\",job=\"$job\"}[$__interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{instance=\"$instance\",job=\"$job\"}[5m]))",
     "legendFormat": "Log Fsyncs"
    }
   ]
  }
 ]
}