---
- name: Monitoring server
  hosts: role_monitoring
  become: true
  roles:
    - { role: base, tags: [base] }
    - { role: pscloud, tags: [cli] }
    - { role: monitoring_stack, tags: [stack] }
    - { role: observability_agent, tags: [agent] }
