---
mysqld_exporter_version: "0.20.0"
mysqld_exporter_arch: linux-amd64
mysqld_exporter_url: >-
  https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.{{ mysqld_exporter_arch }}.tar.gz

mysqld_exporter_bin: /usr/local/bin/mysqld_exporter
mysqld_exporter_config_dir: /etc/mysqld_exporter
mysqld_exporter_user: mysqld_exporter
mysqld_exporter_listen: "127.0.0.1:9104"
