Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20260911.0.0"

  config.vm.provider :libvirt do |lv|
    lv.memory = 4096
    lv.cpus   = 4

    lv.video_type = "virtio"
  end

  config.vm.hostname = "ubuntu2404-kvm"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
end