---
applications: {}
oci_auth_type: instance_principal

db_apps: >-
  {{ applications | dict2items | selectattr('value.database', 'defined') | list }}

db_secret_length: 32
db_user_suffix: _app
db_user_host: "10.20.%"
db_user_pattern: "%_app"

db_user_plugin: caching_sha2_password

db_privileges_default: ALL
db_schema_privileges: {}

db_create_schemas: false
db_schema_encoding: utf8mb4
db_schema_collation: utf8mb4_unicode_ci

db_rotate: false

db_remove_unknown_users: false

db_create_exporter_user: true
db_exporter_host_acl: "10.20.0.%"
db_exporter_max_connections: 3
db_exporter_rotate: false
